main: fr.Indyuce.throwables.Throwables
name: ${project.name}
version: ${project.version}
author: Indyuce
api-version: 1.13

commands:
  throwables:
    description: 'Main command.'

permissions:
  throwables.admin:
    default: op
    description: 'Admin permission.'
